events {}

http {
  map $http_upgrade $proxy_connection {
    default upgrade;
    "" close;
  }

  server {
    listen 80;
    server_tokens off;
    client_max_body_size 100m;

    location /onlyoffice-ds/ {
      proxy_pass http://host.docker.internal:8080/;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $proxy_connection;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $http_host/onlyoffice-ds;

      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      proxy_buffering off;
    }

    location / {
      proxy_pass http://host.docker.internal:8765;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $proxy_connection;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $http_host;

      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
    }
  }
}
